export interface Claim {
  claimId: string; // optional because it's generated by MongoDB
  reason: string;
  customReason?: string;
  explanation: string;
  
  location: {
    street: string;
    city: string;
    state: string;
    pincode: string;
  };

  photos?: string[]; // array of file paths
  policeReport?: string; // file path to police report

  status?: 'OPEN' | 'APPROVED' | 'REJECTED'; // agent status
  rejectionReason?: string; // agent rejection reason

  adminFinalStatus?: 'PENDING' | 'ADMIN_APPROVED' | 'ADMIN_REJECTED'; // admin final status
  adminRejectionReason?: string; // admin rejection reason

  createdAt?: Date;
}
